version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\raggaer\castro

environment:
  GOPATH: c:\gopath

install:
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env

build_script:
  - ps: .\appveyor_build.ps1

artifacts:
  - path: buildOutput\castro.exe
    name: Windows build
  - path: buildOutput\castro
    name: Linux build
