version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\raggaer\castro

environment:
  GOPATH: c:\gopath

install:
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env

build_script:
  - ps: .\appveyor_build.ps1

test: off

artifacts:
  - path: buildOutput\castro_win_amd64.exe
    name: Windows amd64 build
  - path: buildOutput\castro_linux_amd64
    name: Linux amd64 build
  - path: buildOutput\castro_linux_arm64
    name: Linux arm64 build

deploy: off