Mode = "dev"
Port = 8080
Url = "http://localhost"
Datapack = "G:/TFS"
Dialect = "tfs"

[Database]

Username = "root"
Password = "admin"
Name = "castro"

[Cookies]

Name = "castro"
MaxAge = 100000

[Cache]
Default = "5m"
Purge = "1m"

[Custom]

hello = "test"
alvaro = 12